function PlotTPP_3D(perf,value_to_plot)  

if perf.azm ==1
    azm = 360;
    azimuth = linspace(0, 2*pi-(2*pi/azm),azm);
    value_to_plot = repmat(value_to_plot,1,azm);
else
   azm = perf.azm;
   azimuth = perf.azimuth;
end
    
r = [0;perf.r_mid]; % For white space in middle

xx = reshape(bsxfun(@times,r,cos(azimuth)),[],1);
yy = reshape(bsxfun(@times,r,sin(azimuth)),[],1);
zz = reshape([ones(1,azm)*NaN;value_to_plot],[],1);  % NaN added to create white in middle

[xi,yi] = meshgrid(-1.1:0.001:1.1); 
zi = griddata(xx,yy,zz,-yi,-xi); % Flip and rotate axes to follow TPP convention



createfigure(xi,yi,zi)



% figure1 = figure('PaperSize',[4 4],'Color',[1 1 1]);
% 
% axes1 = axes('Parent',figure1,'Position',[3.29589362876076 1.79758336343535 2.77626357429728 3],...
%     'Units','inches');
% hold(axes1,'on');
% 
% surf(xi,yi,zi,'EdgeColor','none','FaceColor','interp');
% colorbar
% colormap jet
% caxis([min(min(zi))*1.25,max(max(zi))*1.25]);
% %contour3(xi,yi,zi,linspace(min(min(zi)),max(max(zi)),20),'k','LineWidth',.15)
% 
% % Plot circle for rotor inner/outer edge
% angle_step=0:0.01:2*pi;
% xo = max(r)*cos(angle_step);
% yo = max(r)*sin(angle_step);
% zo = max(max(zi));
% 
% xi = min(perf.r_mid)*cos(angle_step);
% yi = min(perf.r_mid)*sin(angle_step);
% 
% % plot3(xo,yo,ones(1,length(xo))*zo,'k','linewidth',4); % outer circle
% % plot3(xi,yi,ones(1,length(xo))*zo,'k','linewidth',5); % inner circle
% view(0,90)
% set(gca,'YDir','Reverse')
% set(gca,'YDir','Reverse')
% axis vis3d
% xlim([-1.1 1.1]);
% ylim([-1.1 1.1]);
% hold off
% 
% % Create xlabel
% xlabel('y/R','FontSize',14);
% % Create ylabel
% ylabel('x/R','FontSize',14,'Rotation',90);
% box('on');


% Flow direction marker
%     hold on
%     plot([1.5,1.25],[0,0],'r-','LineWidth',3);
%     plot(1.25,0,'r<', 'MarkerSize',7,'MarkerFaceColor','red');
%     plot([1.25,1.25],[0,.25],'b-','LineWidth',2);
%     plot(1.25,0.25,'b^', 'MarkerSize',7,'MarkerFaceColor','blue')
%     hold off      
%         
%     axis vis3d
%     %axis equal
%     xlabel('x')
%     ylabel('y')
%     zlabel('z') 
%     title('Velocity Distribution Along Blade per Rev (N)')
end


function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 24-Oct-2016 02:36:04

% Create figure
figure('PaperSize',[4 3.5],'Color',[1 1 1]);
colormap(jet);

% Create axes
axes1 = axes('Units','normalized','Position',[0.335 0.325 0.3 0.4]);
hold(axes1,'on');


% Create surf
surf(xdata1,ydata1,zdata1,'FaceColor','interp','EdgeColor','none');

set(gca,'Position',[0.335 0.325 0.3 0.4]); % 0.3 spec doesnt sometimes work!?!?!?! so go set manually
set(gca,'Position',[0.335 0.325 0.3 0.4]);
set(gca,'Position',[0.335 0.325 0.3 0.4]);

% Create xlabel
xlabel('y/R','FontSize',14);

% Create ylabel
ylabel('x/R','FontSize',14,'Rotation',0);

set(gca,'Position',[0.335 0.325 0.3 0.4]);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-1.1 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-1.1 1.1]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'PlotBoxAspectRatio',[1 1 0.909090909090909],...
    'Position',[0.335 0.3 0.3 0.44]);

set(gca,'Position',[0.335 0.325 0.3 0.4]);

% Create colorbar
colorbar('peer',axes1);

% Create textbox
annotation('textbox',...
    [0.355457572502685 0.688816855753644 0.049483351235231 0.0324149108589951],'String',{'CCW'},...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textarrow
annotation('textarrow',[0.370569280343716 0.370569280343716],...
    [0.361426256077795 0.400324149108588],'String',{'V_{\infty}'},'HeadWidth',6,'HeadStyle','plain',...
    'HeadLength',6,...
    'FontName','Arial');
end

